# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: "24"

version: "{build}-{branch}"

init:
  - git config --global core.longpaths true

clone_depth: 1

matrix:
  fast_finish: true

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm test

build: off
